Add Kubelet metrics collect to Kubernetes integration
sensu/catalog pull request #189
Opened 2022-04-19 23:16 UTC by calebhailey

Closes #112

2022-04-20 00:22 UTC, calebhailey commented
This needs to be updated to use the new `http-get` plugin. I'll do that now.

2022-06-22 19:28 UTC, jspaleta commented
Need to finish replacing `wget` with `http-get` everywhere now?  
`http-get` is used in sensu-resources check command references but `wget` is used in the sensu-integration  check command patches

2022-06-22 19:29 UTC, jspaleta requested changes
`wget` usage in sensu-integration needs to be replaced with `http-get` usage to match sensu-resources.

2022-06-22 19:34 UTC, jspaleta commented on integrations/kubernetes/kubernetes-monitoring/sensu-integration.yaml
> +            wget -q -O-
```suggestion
            http-get
```

2022-07-07 19:20 UTC, jspaleta approved these changes

2022-07-07 19:24 UTC, merged