Update Readme with influxdbv2 compatibility info
sensu/catalog pull request #238
Opened 2022-04-28 23:11 UTC by jspaleta

2022-05-03 20:40 UTC, asachs01 requested changes
@jspaleta would it be worth adding more explicit instructions for folks to know what they need to configure with buckets and such?

2022-05-04 22:54 UTC, thoward approved these changes

2022-05-10 22:19 UTC, jspaleta commented
@asachs01 
You have a pointer to more explicitly instructions than the reference I've added?

2022-05-11 16:41 UTC, asachs01 commented
@jspaleta [this issue in the Unpoller repo](https://github.com/unpoller/unpoller/issues/407#issue-1193065803) covers creating the bucket and the requisite Influx config. I think the more detail we add here, the better. This way, users won't have to try and hunt down something when we could have a tailored example ready.

2022-05-11 18:57 UTC, jspaleta commented
@asachs01 
That issue you point to  references the official documentation I've added. 

I'm not sure pointing to an explicit example of how to configure an external service is going to add any value for a new Sensu user beyond the reference to documentation written and supported by the external technology maintainers.  

For example: the desired explicit instructions make reference to the influx cli executables sensu does not provide. I guess we'd also have to add cross platform instructions for the influx cli tool so they could use the explicit example verbatim. 

If we followed this as a common practice for all integrations that require an external service to be pre-configured a specific way...we'd be on the hook for a significant amount of documentation material for technology we interact with.  There is a level of detail for configuring an external service that is out of scope for an integration readme.   

I think pointing to official documentation for high profile "gotcha" external service configuration issues is the right balance.

2022-05-11 21:55 UTC, merged